### ISSUE TITLE
chefdk 0.6.0 + knife-windows 0.8.5 dependency issue

### ISSUE THREAD

**Issue by btm** [chef/knife-windows#236]
From: http://lists.opscode.com/sympa/arc/chef/2015-05/msg00300.html

---

Since this change has occurred; I’m getting some serious dependency issues with winrm-s and knife-ec2/knife windows.

```
No hassles with his version:
$ chef --version
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0

$ chef gem list |egrep 'knife|winrm'
em-winrm (0.6.0)
knife-ec2 (0.10.0)
knife-spork (1.5.0)
knife-windows (0.8.5, 0.8.4)
winrm (1.3.3, 1.3.2, 1.2.0)
winrm-s (0.2.4)
winrm-transport (1.0.0)
```

However with an Out Of the Box ChefDK 0.6.0 (Only since the update to a pessimistic constraint) I get the below errors.
Note: this worked fine with knife-ec2 and knife-windows and all the dependencies with ChefDK 0.6.0 prior to seeing this email about the constraint change.

```
$ chef --version
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

$ chef gem list |egrep 'knife|winrm'
em-winrm (0.6.0)
knife-ec2 (0.10.0)
knife-spork (1.5.0)
knife-windows (0.8.5, 0.8.4)
winrm (1.3.3, 1.2.0)
winrm-s (0.2.4)
winrm-transport (1.0.0)

$ chef verify
Running verification for component 'berkshelf'
Running verification for component 'test-kitchen'
Running verification for component 'chef-client'
Running verification for component 'chef-dk'
Running verification for component 'chefspec'
Running verification for component 'rubocop'
Running verification for component 'fauxhai'
Running verification for component 'knife-spork'
Running verification for component 'kitchen-vagrant'
Running verification for component 'package installation'
.....

/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate winrm-s-0.2.4, because winrm-1.3.3 conflicts with winrm (~> 1.2.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	from /Users/ted/.chefdk/gem/ruby/2.1.0/gems/knife-ec2-0.10.0/lib/chef/knife/ec2_server_create.rb:22:in `<top (required)>'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:127:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:208:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:51:in `load'
	from /opt/chefdk/bin/knife:51:in `<main>'

.../opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:278:in `invalid!': Expected process to exit with [0], but received '1' (Mixlib::ShellOut::ShellCommandFailed)
---- Begin output of /usr/bin/knife exec -E true ----
STDOUT: 
STDERR: /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate winrm-s-0.2.4, because winrm-1.3.3 conflicts with winrm (~> 1.2.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	from /Users/ted/.chefdk/gem/ruby/2.1.0/gems/knife-ec2-0.10.0/lib/chef/knife/ec2_server_create.rb:22:in `<top (required)>'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:127:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:208:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:51:in `load'
	from /usr/bin/knife:51:in `<main>'
---- End output of /usr/bin/knife exec -E true ----
Ran /usr/bin/knife exec -E true returned 1
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:265:in `error!'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/component_test.rb:99:in `block in sh!'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/component_test.rb:99:in `tap'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/component_test.rb:99:in `sh!'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/command/verify.rb:199:in `block (2 levels) in <class:Verify>'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/component_test.rb:78:in `instance_eval'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/component_test.rb:78:in `run_smoke_test'
	from /opt/chefdk/embedded/apps/chef-dk/lib/chef-dk/command/verify.rb:268:in `block (2 levels) in invoke_tests'
```

**Comment by btm** [comment]
I installed chefdk fresh on OS X, then ran `$ chef gem install knife-windows -v 0.8.5 --no-ri --no-rdoc
` and `chef verify` and I didn't see the same issue. Can you provide more information about your platform?

**Comment by btm** [comment]
Even with knife-ec2 installed via `$ chef gem install knife-ec2 --no-ri --no-rdoc` installed, `chef verify` still passes for me.

**Comment by tyler-ball** [comment]
Can you try moving your `~/.chefdk` to `~/.chefdk_old` and see if you get the same issue?

**Comment by epcim** [comment]
the same on ubuntu linux, I actually moved .chefdk to under new name in the morning to resolve another issue. No solution yet.

Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

```
chef gem install chef-metal-ssh
chef gem install chef-provisioning-fog
chef gem install kitchen-ec2
chef gem install chef-metal
chef gem install chef-provisioning
chef gem install knife-openstack
# found knife openstack stoped workign due: Unable to activate winrm-s-0.2.4, because winrm-1.3.3 conflicts with winrm (~> 1.2.0) (Gem::ConflictError)
chef gem uninstall knife-openstack
```

**Comment by btm** [comment]
@epcim can you run `chef gem dependency winrm --reverse-dependencies`?

**Comment by tyler-ball** [comment]
Chef provisioning 1.2.x depends on winrm 1.3, but chef-provisioning 1.1.x depends on winrm 1.2.  We shouldn't be including chef-provisioning 1.2 in the ChefDK (because of exactly this issue).  You also shouldn't need to `chef gem install chef-provisioning` because it is included in the ChefDK.

**Comment by btm** [comment]
I believe an upcoming release of chef-dk is going to bump to chef-provisioning 1.3 and knife-windows 1.0.0 as soon as its ready.

knife-windows 1.0.0.rc.0 is now out, so you could potentially use "chef gem install knife-windows --pre" to get a version of knife-windows that uses winrm 1.3.3+ and resolve your conflict now.

I didn't hear back from the OP on the mailing list. I believe this is now resolved.

**Comment by hiro5id** [comment]
Guys I'm having this same problem, getting this dependency error when running *knife windows*

Unable to activate winrm-s-0.3.1, because winrm-1.2.0 conflicts with winrm (~> 1.3.0) (Gem::ConflictError)

renaming ~/.chefdk  just made it so that there is no Knife command.

How can I resolve this problem ??

**Comment by tyler-ball** [comment]
@hiro5id we're working on a ChefDK 0.7.0 release right now that should resolve this - please watch the blog or mailing list for updates on when it is out!
