### ISSUE TITLE
`knife bootstrap windows winrm` requires a validation.pem 

### ISSUE THREAD

**Issue by burtlo** [chef/knife-windows#261]
I am able to bootstrap nodes without a validation.pem. It seems that it is the actual preferred way to do it now for the usual bootstrapping. 

It seems that it is still required by `knife-windows`. If it is not present the user does not receive a clear message that it is missing.

```
INFO: Using configuration from /Users/franklinwebber/chef-repo/.chef/knife.rb

Waiting for remote response before bootstrap.DEBUG: Adding ec2-54-175-224-12.compute-1.amazonaws.com
DEBUG: :session => :init
DEBUG: :relay_to_servers => echo . & echo Response received.
DEBUG: :relayed => ec2-54-175-224-12.compute-1.amazonaws.com
DEBUG: ec2-54-175-224-12.compute-1.amazonaws.com => :run_command
DEBUG: ec2-54-175-224-12.compute-1.amazonaws.com[F77D5510-AE3B-426D-80FA-CA7B9DEAC058] => :shell_open
DEBUG: ec2-54-175-224-12.compute-1.amazonaws.com[F77D5510-AE3B-426D-80FA-CA7B9DEAC058] => :run_command[echo . & echo Response received.]
DEBUG: :relay_output_from_backend => ["ec2-54-175-224-12.compute-1.amazonaws.com", ". \r\n"]
ec2-54-175-224-12.compute-1.amazonaws.com .
DEBUG: :relay_output_from_backend => ["ec2-54-175-224-12.compute-1.amazonaws.com", "Response received.\r\n"]
ec2-54-175-224-12.compute-1.amazonaws.com Response received.
DEBUG: ec2-54-175-224-12.compute-1.amazonaws.com[F77D5510-AE3B-426D-80FA-CA7B9DEAC058] => :command_cleanup[echo . & echo Response received.]
DEBUG: ec2-54-175-224-12.compute-1.amazonaws.com[F77D5510-AE3B-426D-80FA-CA7B9DEAC058] => :shell_close
DEBUG: :command_complete => ec2-54-175-224-12.compute-1.amazonaws.com with return code 0
DEBUG: command complete on ec2-54-175-224-12.compute-1.amazonaws.com
DEBUG: command complete on All Servers
DEBUG: Exit code found: 0
DEBUG: :unbind => :connection
DEBUG: ec2-54-175-224-12.compute-1.amazonaws.com => :unbind
DEBUG: :unbind_backend => ec2-54-175-224-12.compute-1.amazonaws.com
DEBUG: :session => :close
Remote node responded after 0.01 minutes.
Bootstrapping Chef on ec2-54-175-224-12.compute-1.amazonaws.com
DEBUG: Looking for bootstrap template in /Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap
DEBUG: Found bootstrap template in /Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap windows winrm' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `gsub' for false:FalseClass
```

I was able to create a full backtrace with a little hacking into https://github.com/chef/chef/blob/master/lib/chef/knife.rb#L449 to include the ` ui.info  "Exception: #{e.backtrace.join("\n")}"`

```
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap windows winrm' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `gsub' for false:FalseClass
Exception: /Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/core/windows_bootstrap_context.rb:243:in `escape_and_echo'
/Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/core/windows_bootstrap_context.rb:45:in `validation_key'
(erubis):189:in `block in evaluate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
/Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap_windows_base.rb:154:in `render_template'
/Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap_windows_base.rb:199:in `create_bootstrap_bat_command'
/Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap_windows_base.rb:170:in `bootstrap'
/Users/franklinwebber/.chefdk/gem/ruby/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap_windows_winrm.rb:41:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
/opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
/opt/chefdk/bin//knife:51:in `load'
/opt/chefdk/bin//knife:51:in `<main>'
```

This backtrace line numbers seem to no longer be synchronized. But I think the issue still persists. The problem is the returning of `false` when the validation key is missing. Which essentially gets the gsub message sent to it.

https://github.com/chef/knife-windows/blob/master/lib/chef/knife/core/windows_bootstrap_context.rb#L55-L59

**Comment by asebastian-r7** [comment]
We are running into this issue as well, can no longer bootstrap nodes since we went validatorless.

**Comment by asebastian-r7** [comment]
@burtlo was able to get around this issue by installing the prerelease version (1.0.0.rc.1), which supports validatorless bootstraps. 
`gem install --pre knife-windows`

Also needed to wipe out my existing knife-windows gems.

**Comment by ksubrama** [comment]
Yes, we have implemented support for validator-less bootstrapping in knife-1.0.0 but there is still some testing to be done before we release it.
