### ISSUE TITLE
knife-windows gem version >= 0.8.6 have problems with Windows find cmd

### ISSUE THREAD

**Issue by kokovoj** [chef/knife-windows#358]
All knife-windows gem versions between 0.8.6 and 1.4.0 inclusive (ie. `knife-windows (1.4.0, 1.3.0, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.8.6`) have this issue, where the gem can't handle Windows `find` cmd when it's part of the cmd executed on the remote Windows Server 2008 R2 machine.
Ex. 
``` 
$ knife winrm XXX-YYY.ZZZ.com -x user -P "XXXXXXXXX" -p 8888 "wmic product get name | find \"Java\""
ERROR: Failed to execute command on XXX-YYY.ZZZ.com return code 1
```
Very verbose version
``` 
$ knife winrm "name:XXX-YYY.ZZZ.com" -x user -P "XXXXXXXXX" -p 8888 "wmic product get name | find \"Java\"" -VV
INFO: Using configuration from XXXXXXXXX
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as XXXXXXXXX
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://my_chef_server/search/node?q=name:XXX-YYY.ZZZ.com&sort=X_CHEF_id_CHEF_X%20asc&start=0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: XXXXXXXXX
DEBUG: X-OPS-TIMESTAMP: 2016-04-07T20:04:38Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: XXXXXXX
DEBUG: X-OPS-AUTHORIZATION-2: XXXXXXX
DEBUG: X-OPS-AUTHORIZATION-3: XXXXXXX
DEBUG: X-OPS-AUTHORIZATION-4: XXXXXXX
DEBUG: X-OPS-AUTHORIZATION-5: XXXXXXX
DEBUG: X-OPS-AUTHORIZATION-6: XXXXXXX
DEBUG: HOST: my_chef_server:443
DEBUG: X-REMOTE-REQUEST-ID: XXXXXXXXX
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: XXXXXXX/XXXXXXX
DEBUG: date: Thu, 07 Apr 2016 19:56:09 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=osc;version=11.0.2;erchef=1.2.6
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Adding XXX-YYY.ZZZ.com
DEBUG: :session => :init
DEBUG: :relay_to_servers => wmic product get name | find "Java"
DEBUG: :relayed => XXX-YYY.ZZZ.com
DEBUG: XXX-YYY.ZZZ.com => :run_command
DEBUG: XXX-YYY.ZZZ.com[XXXXXXXXXXXX] => :shell_open
DEBUG: XXX-YYY.ZZZ.com[XXXXXXXXXXXX] => :run_command[wmic product get name | find "Java"]
DEBUG: XXX-YYY.ZZZ.com[XXXXXXXXXXXX] => :command_cleanup[wmic product get name | find "Java"]
DEBUG: XXX-YYY.ZZZ.com[XXXXXXXXXXXX] => :shell_close
DEBUG: :command_complete => XXX-YYY.ZZZ.com with return code 1
DEBUG: command complete on XXX-YYY.ZZZ.com
DEBUG: command complete on All Servers
DEBUG: Exit code found: 1
ERROR: Failed to execute command on XXX-YYY.ZZZ.com return code 1
DEBUG: :unbind => :connection
DEBUG: XXX-YYY.ZZZ.com => :unbind
DEBUG: :unbind_backend => XXX-YYY.ZZZ.com
DEBUG: :session => :close
```
Note that excluding the find part from the cmd, works, ie.
```
$ knife winrm XXX-YYY.ZZZ.com -x user -P "XXXXXXXXX" -p 8888 "wmic product get name"
XXX-YYY.ZZZ.com Name
...
XXX-YYY.ZZZ.com Java 7 Update 79 (64-bit)
...
```
Another example of the failure (although this time there is no exit code of 1, but it still fails to work correctly)
```
$ knife winrm XXX-YYY.ZZZ.com -x user -P "XXXXXXXXX" -p 8888 "echo "foo" | find \"foo\""
$
``` 

In contrast, earlier versions (specifically versions 0.8.5, 0.8.4, and 0.6.0) do handle "find" cmd correctly, ie. : 
```
$ knife winrm XXX-YYY.ZZZ.com -x user -P "XXXXXXXXX" -p 8888 "wmic product get name | find \"Java\""
XXX-YYY.ZZZ.com Java 7 Update 79 (64-bit)
XXX-YYY.ZZZ.com
```
and
```
$ knife winrm XXX-YYY.ZZZ.com -x user -P "XXXXXXXXX" -p 8888 "echo "foo" | find \"foo\""
XXX-YYY.ZZZ.com foo
```

Is there a workaround for versions >= 0.8.6 ?

**Comment by mwrock** [comment]
I'm not able to replicate this:
```
C:\> knife winrm -m 192.168.137.155 -x vagrant -P vagrant 'wmic product get name | find \"Chef\"'
192.168.137.155 Chef Client v12.8.1
```

What happens if you run that command in a cmd.exe window on the node?

One suspision I have is that the find.exe in your node's path is not `c:\windows\system32\find.exe` but something else. I don't know why, but chefdk ships with a different version and if you have chefdk on the node, it might be trying to use `c:\opscode\chefdk\embedded\bin\find.exe`.

**Comment by WeekendsBull** [comment]
Hi @mwrock, 

I'm having the similar issue that I'm running knife bootstrap windows winrm command on windows. 
We never had this issue knife-windows v0.6.0 that now things got migrated to Chef 12 which runs on knife-windows v1.4.0. 

I'm running the command to bootstrap as below to install the latest chef-client (tested 12.4.1, 12.7.2 and 12.8.0). However, it works randomly and failed mostly with winrm authentication error, "WinRMAuthorizationError". I ran the same command between AWS instances to make sure the issue doesn't occur in our network. I was able to bootstrap one instance and failed on the other instance which has been the same behavior in past few days. 

"knife bootstrap windows winrm $ip -x $userName -P "$password" -N $nodeName -r "$runList" --secret-file .\encrypted_data_bag_secret -E  "$environment" --bootstrap-version "12.9.38-1" -V" 

[00:31:00]DEBUG: ---- End HTTP Status/Header Data ----
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
[00:31:00]DEBUG: Content-Length validated correctly.
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
[00:31:00]DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
[00:31:00]
[00:31:00]Waiting for remote response before bootstrap.DEBUG: echo . & echo Response received.
[00:31:32]..DEBUG: echo . & echo Response received.
[00:32:03]..DEBUG: echo . & echo Response received.
[00:32:34]..DEBUG: echo . & echo Response received.
[00:33:05]..DEBUG: echo . & echo Response received.
[00:33:14]DEBUG: Looking for key winrm_user and found value Administrator
[00:33:14]ERROR: Failed to authenticate to xx.xxx.xxx.xxx as Administrator
[00:33:14]Response: WinRM::WinRMAuthorizationError
[00:33:14]Hint: Make sure to prefix domain usernames with the correct domain name.
[00:33:14]Hint: Local user names should be prefixed with computer name or IP address.
[00:33:14]EXAMPLE: my_domain\user_namer
[00:33:14]ERROR: No response received from remote node after 2.22 minutes, giving up.
[00:33:14]ERROR: Exception: WinRM::WinRMAuthorizationError
[00:33:14]C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/response_handler.rb:57:in `raise_if_auth_error': WinRM::WinRMAuthorizationError (WinRM::WinRMAuthorizationError)
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/response_handler.rb:50:in `raise_if_error'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/response_handler.rb:35:in `parse_to_xml'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/transport.rb:198:in `send_request'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/http/transport.rb:193:in `send_request'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/winrm_service.rb:489:in `send_message'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/winrm-1.7.3/lib/winrm/winrm_service.rb:150:in `open_shell'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_session.rb:49:in `relay_command'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_knife_base.rb:130:in `block in relay_winrm_command'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_knife_base.rb:128:in `each'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_knife_base.rb:128:in `relay_winrm_command'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_knife_base.rb:114:in `run_command'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/bootstrap_windows_winrm.rb:70:in `wait_for_remote_response'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/bootstrap_windows_base.rb:329:in `bootstrap'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/bootstrap_windows_winrm.rb:53:in `run'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/knife.rb:219:in `run'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/application/knife.rb:148:in `run'
[00:33:14]	from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/bin/knife:25:in `<top (required)>'
[00:33:14]	from C:/opscode/chef/embedded/bin/knife:22:in `load'
[00:33:14]	from C:/opscode/chef/embedded/bin/knife:22:in `<main>'
[00:33:14]bootstrapping successfully completed
[00:33:14]Provisioning complete!

**Comment by mwrock** [comment]
@WeekendsBull this looks like a separate problem (winrm authorization) than what this issue is addressing (the `find`) command. Would you mind openning a new issue and I'd be happy to respond there? Thanks!!

**Comment by WeekendsBull** [comment]
Thank you for your quick response, @mwrock.
Enabling validation didn't work for me :(  By the way, I have been watched several posts in your blog and would like to say "Thank you". I have currently submitted the issue of mine to the Chef Support and working with the Chef engineer. I will submit a new ticket.

**Comment by btm** [comment]
If you need further help, please post a message in the 'chef' category on [Discourse ](https://discourse.chef.io/ )instead of filing an issue here.

https://discourse.chef.io/
