### ISSUE TITLE
chef/knife/winrm_knife_base (LoadError)

### ISSUE THREAD

**Issue by mlcooper** [chef/knife-windows#359]
I'm receiving the error below when I try to use a gem that was written in house, which has always worked in the past for me.  I had the dev team look at this stack trace and they feel it may be an issue with `knife-windows`.

My environment:
```
[redacted@localhost gems]$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```
Error:
```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- chef/knife/winrm_knife_base (LoadError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/coopem67/.chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/bootstrap_windows_winrm.rb:22:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/core/subcommand_loader.rb:100:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/core/subcommand_loader.rb:100:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/core/subcommand_loader.rb:100:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/core/subcommand_loader.rb:100:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/core/subcommand_loader.rb:110:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/core/subcommand_loader.rb:124:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
	from /bin/knife:49:in `load'
	from /bin/knife:49:in `<main>'
```

**Comment by mwrock** [comment]
I'd assume that `/home/coopem67/.chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.0/lib/chef/knife/winrm_knife_base.rb` exists on your machine. Sounds like its probably a conflict with something in your in house gem constraints.

**Comment by mlcooper** [comment]
Thanks...you're correct.  We have a very old constraint of `knife-windows` in our gem (I will find out why from the dev team).  I changed it to `~> 1.4.0` and our gem now works.
