### ISSUE TITLE
knife winrm fails with undefined method 'echo=' error

### ISSUE THREAD

**Issue by btm** [chef/knife-windows#513]
# Version:

Chef Workstation 21.1.222
Chef Workstation 21.2.303 (Infra Client 16.10.17)

# Environment:

Windows 10

# Scenario:

`knife winrm` is broken and raises an error

# Steps to Reproduce:

```
knife winrm -VVV
```

# Expected Result:

`knife winrm` can be used to run commands on a remote system using search.

# Actual Result:

`knife winrm` crashes

```
> knife winrm -VVV
Traceback (most recent call last):
        16: from C:/opscode/chef-workstation/bin/knife:371:in `<main>'
        15: from C:/opscode/chef-workstation/bin/knife:371:in `load'
        14: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/bin/knife:24:in `<top (required)>'
        13: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/lib/chef/application/knife.rb:165:in `run'
        12: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/lib/chef/knife.rb:229:in `run'
        11: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/lib/chef/knife.rb:489:in `run_with_pretty_exceptions'
        10: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
         9: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/lib/chef/knife.rb:490:in `block in run_with_pretty_exceptions'
         8: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-windows-4.0.6/lib/chef/knife/winrm.rb:49:in `run'
         7: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-windows-4.0.6/lib/chef/knife/helpers/winrm_knife_base.rb:59:in `configure_session'
         6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-windows-4.0.6/lib/chef/knife/helpers/winrm_knife_base.rb:221:in `resolve_session_options'
         5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-windows-4.0.6/lib/chef/knife/helpers/winrm_knife_base.rb:287:in `get_password'
         4: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.10.17-universal-mingw32/lib/chef/knife/core/ui.rb:176:in `ask'
         3: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/tty-prompt-0.23.0/lib/tty/prompt.rb:202:in `ask'
         2: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/tty-prompt-0.23.0/lib/tty/prompt.rb:181:in `invoke_question'
         1: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/tty-prompt-0.23.0/lib/tty/prompt/question.rb:109:in `call'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-windows-4.0.6/lib/chef/knife/helpers/winrm_knife_base.rb:287:in `block in get_password': undefined method `echo=' for #<TTY::Prompt::Question @message=Enter your password: , @input=> (NoMethodError)
Did you mean?  echo
               echo?
```

See also: https://github.com/chef/customer-bugs/issues/403

**Comment by sanga1794** [comment]
Closing the issue as PR: https://github.com/chef/knife-windows/pull/514 got merged!!
